export default [
  {
    login: "kmust-why",
    id: 29390551,
    node_id: "MDQ6VXNlcjI5MzkwNTUx",
    avatar_url: "https://avatars2.githubusercontent.com/u/29390551?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kmust-why",
    html_url: "https://github.com/kmust-why",
    followers_url: "https://api.github.com/users/kmust-why/followers",
    following_url:
      "https://api.github.com/users/kmust-why/following{/other_user}",
    gists_url: "https://api.github.com/users/kmust-why/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/kmust-why/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kmust-why/subscriptions",
    organizations_url: "https://api.github.com/users/kmust-why/orgs",
    repos_url: "https://api.github.com/users/kmust-why/repos",
    events_url: "https://api.github.com/users/kmust-why/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/kmust-why/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Bech007",
    id: 17314477,
    node_id: "MDQ6VXNlcjE3MzE0NDc3",
    avatar_url: "https://avatars1.githubusercontent.com/u/17314477?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Bech007",
    html_url: "https://github.com/Bech007",
    followers_url: "https://api.github.com/users/Bech007/followers",
    following_url:
      "https://api.github.com/users/Bech007/following{/other_user}",
    gists_url: "https://api.github.com/users/Bech007/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Bech007/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Bech007/subscriptions",
    organizations_url: "https://api.github.com/users/Bech007/orgs",
    repos_url: "https://api.github.com/users/Bech007/repos",
    events_url: "https://api.github.com/users/Bech007/events{/privacy}",
    received_events_url: "https://api.github.com/users/Bech007/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Ashutosh619-sudo",
    id: 55102089,
    node_id: "MDQ6VXNlcjU1MTAyMDg5",
    avatar_url: "https://avatars1.githubusercontent.com/u/55102089?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ashutosh619-sudo",
    html_url: "https://github.com/Ashutosh619-sudo",
    followers_url: "https://api.github.com/users/Ashutosh619-sudo/followers",
    following_url:
      "https://api.github.com/users/Ashutosh619-sudo/following{/other_user}",
    gists_url: "https://api.github.com/users/Ashutosh619-sudo/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Ashutosh619-sudo/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Ashutosh619-sudo/subscriptions",
    organizations_url: "https://api.github.com/users/Ashutosh619-sudo/orgs",
    repos_url: "https://api.github.com/users/Ashutosh619-sudo/repos",
    events_url:
      "https://api.github.com/users/Ashutosh619-sudo/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Ashutosh619-sudo/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nadralia",
    id: 38062858,
    node_id: "MDQ6VXNlcjM4MDYyODU4",
    avatar_url: "https://avatars3.githubusercontent.com/u/38062858?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nadralia",
    html_url: "https://github.com/nadralia",
    followers_url: "https://api.github.com/users/nadralia/followers",
    following_url:
      "https://api.github.com/users/nadralia/following{/other_user}",
    gists_url: "https://api.github.com/users/nadralia/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nadralia/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nadralia/subscriptions",
    organizations_url: "https://api.github.com/users/nadralia/orgs",
    repos_url: "https://api.github.com/users/nadralia/repos",
    events_url: "https://api.github.com/users/nadralia/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/nadralia/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hexangel616",
    id: 4047984,
    node_id: "MDQ6VXNlcjQwNDc5ODQ=",
    avatar_url: "https://avatars2.githubusercontent.com/u/4047984?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hexangel616",
    html_url: "https://github.com/hexangel616",
    followers_url: "https://api.github.com/users/hexangel616/followers",
    following_url:
      "https://api.github.com/users/hexangel616/following{/other_user}",
    gists_url: "https://api.github.com/users/hexangel616/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hexangel616/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hexangel616/subscriptions",
    organizations_url: "https://api.github.com/users/hexangel616/orgs",
    repos_url: "https://api.github.com/users/hexangel616/repos",
    events_url: "https://api.github.com/users/hexangel616/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hexangel616/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gauravgutholia",
    id: 49594934,
    node_id: "MDQ6VXNlcjQ5NTk0OTM0",
    avatar_url: "https://avatars2.githubusercontent.com/u/49594934?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gauravgutholia",
    html_url: "https://github.com/gauravgutholia",
    followers_url: "https://api.github.com/users/gauravgutholia/followers",
    following_url:
      "https://api.github.com/users/gauravgutholia/following{/other_user}",
    gists_url: "https://api.github.com/users/gauravgutholia/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/gauravgutholia/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/gauravgutholia/subscriptions",
    organizations_url: "https://api.github.com/users/gauravgutholia/orgs",
    repos_url: "https://api.github.com/users/gauravgutholia/repos",
    events_url: "https://api.github.com/users/gauravgutholia/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/gauravgutholia/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "rahuldkjain",
    id: 26406279,
    node_id: "MDQ6VXNlcjI2NDA2Mjc5",
    avatar_url: "https://avatars1.githubusercontent.com/u/26406279?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rahuldkjain",
    html_url: "https://github.com/rahuldkjain",
    followers_url: "https://api.github.com/users/rahuldkjain/followers",
    following_url:
      "https://api.github.com/users/rahuldkjain/following{/other_user}",
    gists_url: "https://api.github.com/users/rahuldkjain/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/rahuldkjain/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rahuldkjain/subscriptions",
    organizations_url: "https://api.github.com/users/rahuldkjain/orgs",
    repos_url: "https://api.github.com/users/rahuldkjain/repos",
    events_url: "https://api.github.com/users/rahuldkjain/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/rahuldkjain/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "cmcodes1",
    id: 34341671,
    node_id: "MDQ6VXNlcjM0MzQxNjcx",
    avatar_url: "https://avatars1.githubusercontent.com/u/34341671?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/cmcodes1",
    html_url: "https://github.com/cmcodes1",
    followers_url: "https://api.github.com/users/cmcodes1/followers",
    following_url:
      "https://api.github.com/users/cmcodes1/following{/other_user}",
    gists_url: "https://api.github.com/users/cmcodes1/gists{/gist_id}",
    starred_url: "https://api.github.com/users/cmcodes1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/cmcodes1/subscriptions",
    organizations_url: "https://api.github.com/users/cmcodes1/orgs",
    repos_url: "https://api.github.com/users/cmcodes1/repos",
    events_url: "https://api.github.com/users/cmcodes1/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/cmcodes1/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Singh-Shivani",
    id: 47295558,
    node_id: "MDQ6VXNlcjQ3Mjk1NTU4",
    avatar_url: "https://avatars3.githubusercontent.com/u/47295558?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Singh-Shivani",
    html_url: "https://github.com/Singh-Shivani",
    followers_url: "https://api.github.com/users/Singh-Shivani/followers",
    following_url:
      "https://api.github.com/users/Singh-Shivani/following{/other_user}",
    gists_url: "https://api.github.com/users/Singh-Shivani/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Singh-Shivani/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Singh-Shivani/subscriptions",
    organizations_url: "https://api.github.com/users/Singh-Shivani/orgs",
    repos_url: "https://api.github.com/users/Singh-Shivani/repos",
    events_url: "https://api.github.com/users/Singh-Shivani/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Singh-Shivani/received_events",
    type: "User",
    site_admin: false,
  },
];
