export default {
  login: "Pratyush2710",
  id: 30828006,
  node_id: "MDQ6VXNlcjMwODI4MDA2",
  avatar_url: "https://avatars3.githubusercontent.com/u/30828006?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Pratyush2710",
  html_url: "https://github.com/Pratyush2710",
  followers_url: "https://api.github.com/users/Pratyush2710/followers",
  following_url:
    "https://api.github.com/users/Pratyush2710/following{/other_user}",
  gists_url: "https://api.github.com/users/Pratyush2710/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Pratyush2710/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Pratyush2710/subscriptions",
  organizations_url: "https://api.github.com/users/Pratyush2710/orgs",
  repos_url: "https://api.github.com/users/Pratyush2710/repos",
  events_url: "https://api.github.com/users/Pratyush2710/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Pratyush2710/received_events",
  type: "User",
  site_admin: false,
  name: "Pratyush Garg",
  company: null,
  blog: "",
  location: "PDPM IIITDM-Jabalpur",
  email: null,
  hireable: null,
  bio: " Developer || Programmer || Instrumentalist ",
  twitter_username: null,
  public_repos: 52,
  public_gists: 0,
  followers: 10,
  following: 32,
  created_at: "2017-08-08T09:19:16Z",
  updated_at: "2020-07-22T19:22:06Z",
};
